### ISSUE TITLE
Persisting error message

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#199] opened 2018-01-24 03:40 UTC
When I have created an opportunity 
And I have missed a field
Then an error message appears 
And when I have filled in all of the fields
Then the error message still shows but this time has no instructions
![image](https://user-images.githubusercontent.com/11237533/35313444-3c3f1718-0075-11e8-9ccc-1fe99ebb5d06.png)

**Comment by mark-a-wilson** [comment] 2018-01-25 00:02
I believe this was a duplicate of #204 

I just re-tested this in TEST and:

Saved a draft opportunity with some fields incomplete (result: got the "You can't publish..." warning) - ✅
Went back in and completed all the fields and re-saved (result: warning message was no longer present, and the publish button was available) ✅
🥇

**Closed by mark-a-wilson** 2018-01-25 00:02 UTC
Labels: bug, complete
